"""Update ChatHistory model fields

Revision ID: d6e35b1ec1a5
Revises: d7e630e2e507
Create Date: 2025-05-06 00:59:06.055215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6e35b1ec1a5'
down_revision: Union[str, None] = 'd7e630e2e507'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_history', sa.Column('role', sa.String(length=50), nullable=False))
    op.add_column('chat_history', sa.Column('content', sa.Text(), nullable=False))
    op.drop_column('chat_history', 'message_text')
    op.drop_column('chat_history', 'is_user_message')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_history', sa.Column('is_user_message', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('chat_history', sa.Column('message_text', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('chat_history', 'content')
    op.drop_column('chat_history', 'role')
    # ### end Alembic commands ###
